"""initial schema

Revision ID: 899dc789c498
Revises: 
Create Date: 2026-05-09 16:45:22.521096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899dc789c498'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    boolean_false_default = (
        sa.text("false") if bind.dialect.name == "postgresql" else sa.text("0")
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.String(length=2), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('flag_emoji', sa.Text(), nullable=True),
    sa.Column('wikidata_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingest_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('election_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elections',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('country_id', sa.String(length=2), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('election_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'upcoming'"), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('wikipedia_url', sa.Text(), nullable=True),
    sa.Column('wikidata_id', sa.Text(), nullable=True),
    sa.Column('turnout_pct', sa.Float(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('country_id', sa.String(length=2), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('short_name', sa.Text(), nullable=True),
    sa.Column('color_hex', sa.Text(), nullable=True),
    sa.Column('wikidata_id', sa.Text(), nullable=True),
    sa.Column('ideology', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('election_id', sa.Text(), nullable=True),
    sa.Column('party_id', sa.Text(), nullable=True),
    sa.Column('vote_share', sa.Float(), nullable=True),
    sa.Column('seats_won', sa.Integer(), nullable=True),
    sa.Column('votes_raw', sa.Integer(), nullable=True),
    sa.Column('is_governing', sa.Boolean(), server_default=boolean_false_default, nullable=False),
    sa.Column('result_type', sa.Text(), server_default=sa.text("'final'"), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('parties')
    op.drop_table('elections')
    op.drop_table('ingest_log')
    op.drop_table('countries')
    # ### end Alembic commands ###
